version: '3.7'

services:
  web:
    build: .
    command: gunicorn blog_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
    - db

  db:
    image: postgres:11
